### PR TITLE
Fatemeh Kalantari SiN submission

### PR DESCRIPTION
**Pull request by F-kalantari95**

### CODE REVIEW

**Comment by lukasc-ubc** [comment]
We are very tight on space, so am I not sure if we will be able to fit all the submissions.  I will do my best.

Please remove the file in the main folder.  Files should only go in the "submissions" folder.

**Comment by lukasc-ubc** [comment]
Can you please reduce the floorplan, and make the design more space efficient?  We are low on space.

**Comment by F-kalantari95** [comment]
Hi Lukas,

Thanks for your reply,
The file in the main folder is removed and the one in the submission folder
is the final one. The final design is in the submission folder, with the
same name. I added this design to explore SiN fab as you suggested, so I’d
appreciate it if you could squeeze it as it would be a good chance for me.

Thanks in advance,
Fatemeh

**Comment by F-kalantari95** [comment]
What would be the desired floor plan size?
Let me know so that I can reduce accordingly.

Regards,
Fatemeh

**Comment by lukasc-ubc** [comment]
600 µm wide would be ideal, since I have a column of such designs.  just remove the white space by moving things around.
thanks!

**Comment by lukasc-ubc** [comment]
there should only be a single top cell.

image

**Pull request merged**
