### PR TITLE
Add new file

### PR DESCRIPTION
**Pull request by newmansc2**

### CODE REVIEW

**Comment by newmansc2** [comment]
"[Merge branch 'SiEPIC:main' into main](https://github.com/SiEPIC/openEBL-2024-10-SiN/pull/4/commits/291f33cc6ec216029e2272f05da40786bf7f2277)"

This commit was an accident.  Not sure if it does anything.  Please reject my pull request if it is a problem.

**Comment by lukasc-ubc** [comment]
Applied Nanotools asked us to change to Layer 4/0.  I have updated the SiEPIC EBeam PDK.

I updated your design accordingly.

**Comment by newmansc2** [comment]
thank you

**Comment by newmansc2** [comment]
I was not able to update the SiEPIC EBeam PDK using the KLayout package manager.  It didn't give me the option to download the latest version (v0.4.20).  However, I updated the PDK manually by cloning the repo and copying the files to my KLayout directory.

**Pull request merged**
