### PR TITLE
Add new designs

### PR DESCRIPTION
**Pull request by newmansc2**
I updated the SiEPIC EBeam PDK to v0.4.20 (manually by cloning the repo and copying the files).  

SiN still appears to be on layer 5 (if I understand correctly).  Please advise.

### CODE REVIEW

**Comment by lukasc-ubc** [comment]
Strange. Can you check the EBeam.lyt file has 4/0 for SiN, and restart KLayout?

image

**Comment by lukasc-ubc** [comment]
I just updated the PDK in KLayout's Salt Package manager.  It may be that you still have the old one installed?  Check that the library has the right version number.

image

**Comment by newmansc2** [comment]
It works now.  I updated the SiEPIC EBeam PDK to v0.4.21 using the KLayout package manager.  

image

image

**Comment by newmansc2** [comment]
thank you

**Comment by newmansc2** [comment]
Closing to fix the files.

**Pull request closed without merging**
