### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by Amesh-Kahloon-Calgary-Account**

### CODE REVIEW

**Comment by lukasc-ubc** [comment]
There are many errors in your design.  Did you go through the "v" verification?

Please make sure there are no errors.

**Comment by lukasc-ubc** [comment]
@Amesh-Kahloon-Calgary-Account

**Comment by Amesh-Kahloon-Calgary-Account** [comment]
Hi Lukas, the errors are from pin issues and connectivety when I use a 1550 nm wavelength SiN grating coupler connected towards a taper. I tried to fix the issue but the grating coupler always snaps to the other end of the taper. The example layout you posted for the 1550 nm wavelength SiN grating coupler connected to a SiN taper also had the same errors when I run the "v" verification on KLayout. This issue does not happen for the 1330 nm wavelength case.

**Comment by lukasc-ubc** [comment]
Please update your EBeam PDK and SiEPIC-Tools.  The issue of the pin on the GC was fixed last week.

**Comment by lukasc-ubc** [comment]
@Amesh-Kahloon-Calgary-Account

**Comment by lukasc-ubc** [comment]
Closing this pull request.  Please re-open and submit if you wish to have this fabricated.

regards
Lukas

**Pull request closed without merging**
