### PR TITLE
new and updated designs

### PR DESCRIPTION
**Pull request by newmansc2**
Updated CDC design using s-bends and new CDC designs with s-bends

### CODE REVIEW

**Comment by lukasc-ubc** [comment]
Hi Scott,

I am wondering why you aren't using the CDC that includes the S-bend inside?  This avoids the overlapping errors you have.

image
image

**Comment by newmansc2** [comment]
Hi Lukas - I didn't use the CDC p-cell with an S-bends (contra_directional_coupler) because I thought I saw in another thread that it had an issue with 0.75um WG width.  I just tested that p-cell and I see that it works with the 0.75um WG width.  

However, I am iterating on a baseline CDC design (for which we have data) that uses the Contra_DC_custom p-cell and has non-equal inner and outer corrugation widths.  I am hesitant to switch to the contra_directional_coupler p-cell, which only has equal inner/outer corrugation widths.  I don't know what impact this parameter will have on device performance.

**Comment by newmansc2** [comment]
Here is the comment on the CDC p-cell issue I was referring to:
https://github.com/SiEPIC/SiEPIC_EBeam_PDK/issues/301

**Comment by lukasc-ubc** [comment]
@mustafacc, what do you think?

**Comment by newmansc2** [comment]
Withdrawing.  I will rework using the contra_directional_couplerp-cell with s-bends (with symmetric corrugation) to satisfy DRC.

**Pull request closed without merging**
