### PR TITLE
SiN waveguide test

### PR DESCRIPTION
**Pull request by caelrw**
[NEW] Three MZIs in EBeam_cael3_v3.gds using 800 nm width waveguides. 

[OLD] Simple waveguides at 1310 nm wavelength with 750 nm width to compare bend losses.
Both files checked with no verification errors.

### CODE REVIEW

**Comment by lukasc-ubc** [comment]
Great that you were able to complete a design.  Could you please describe what information you expect to learn from the experiments with this design?  There are similar designs on the chip already, specifically in the four corners you will find loopbacks.

**Comment by caelrw** [comment]
I was hoping to study the losses. I wanted to make similar simple MZI
structures, and possibly a ring resonator. The MZIs would be similar if I
can submit them on time without errors. Is that alright?

**Comment by lukasc-ubc** [comment]
Yes, please go ahead, and submit by Sunday night. thanks!

**Comment by caelrw** [comment]
This concludes all of the files I intend to submit for this pull request and the SiN run.

**Pull request merged**
