### PR TITLE
Resubmit correct files

### PR DESCRIPTION
**Pull request by Amesh-Kahloon-Calgary-Account**

### CODE REVIEW

**Comment by lukasc-ubc** [comment]
We are very tight on space, so am I not sure if we will be able to fit all the submissions.  I will do my best.

**Comment by lukasc-ubc** [comment]
This design uses very small bend radii for the 1 µm wide waveguides.  Do you know how much loss these will introduce?  We are using 50 µm for the 750 nm waveguides, so 1 µm will need more than this. You have many circuits with 25 to 30 µm.

**Comment by Amesh-Kahloon-Calgary-Account** [comment]
Yes, I am aware of the loss for the layout. The purpose for these designs are to see the transmission for these specific radii for other wafers we have in lab.

**Comment by Amesh-Kahloon-Calgary-Account** [comment]
The purpose is actually to determine the loss and transmission for those layout.

**Pull request merged**
