### PR TITLE
Add new designs

### PR DESCRIPTION
**Pull request by newmansc2**
CDCA6 is like CDCA1 but uses s-bends.

I will rework the other designs (CDCA3-5) with s-bends if time permits.

### CODE REVIEW

**Comment by newmansc2** [comment]
@lukasc-ubc Is 10/21 a hard deadline for this run?  Or will you accept late submissions?  In any case, we appreciate the opportunity to submit designs for this fab run.

**Comment by newmansc2** [comment]
Cancelling to submit updated versions of these designs.

**Comment by lukasc-ubc** [comment]
We will grant more time. Lukas ChrostowskiProfessor, Electrical and Computer EngineeringUniversity of British ColumbiaQuantum Matter InstituteMember, College of the Royal Society of Canadahttp://siepic.ca Silicon Photonicshttp://quantum-bc.ca Quantum Computing CREATE programhttps://qmi.ubc.ca/about/directory/lukas-chrostowskiOn Oct 21, 2024, at 13:43, newmansc2 ***@***.***> wrote:﻿
@lukasc-ubc Is 10/21 a hard deadline for this run?  Or will you accept late submissions?  In any case, we appreciate the opportunity to submit designs for this fab run.

**Comment by lukasc-ubc** [comment]
November 4 deadline!

**Pull request closed without merging**
